name: event_booking
description: A Flutter Event Booking Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  go_router: ^14.2.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  carousel_slider_plus: ^7.0.1
  font_awesome_flutter: ^10.6.0
  flutter_animate: ^4.3.0
  fl_chart: ^0.66.0
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
